# app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anotherapp
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: anotherapp
  template:
    metadata:
      name: anotherapp
      labels:
        app: anotherapp
    spec:
      containers:
        - name: webserver
          image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
