apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <my github repository url>
    path: helm/myapp
    targetRevision: main
    helm:
      valueFiles:
        - environments/production-east/values.yaml
        - environments/production-east/version.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
