apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rxintake
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shameson/argo-demo
    path: helm/rxintake/environments/release
    targetRevision: main
    helm:
      valueFiles:
      - /helm/rxintake/environments/release/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rxintake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
